### ISSUE TITLE
Problem with Arduino IDE

### ISSUE THREAD

**Issue by Schulz19** [Securethingsuk/Heltec_CubeCell#1]
Arduino 1.8.7; CubeCell Dev Boards 0.0.4

Example: LoRaWan_BME280_THP

Error Message

WARNUNG: Kategorie 'SSD1306' in der Bibliothek SSD1306 OLED ist ungültig und wird auf 'Uncategorized' festgelegt
LoRaWan_BME280_THP:93:39: error: 'uint16_t GetBatteryVoltage()' was declared 'extern' and later 'static' [-fpermissive]

 static uint16_t GetBatteryVoltage(void)

                                       ^

In file included from D:\BK-Schulz\DIT\Heltec ASR650x\BMP280\Heltec_CubeCell-master\LoRaWan_BME280_THP\LoRaWan_BME280_THP.ino:10:0:

C:\Users\Schulz\AppData\Local\Arduino15\packages\CubeCell\hardware\CubeCell\0.0.4\libraries\LoRa\src/LoRaWan_APP.h:61:21: note: previous declaration of 'uint16_t GetBatteryVoltage()'

 extern "C" uint16_t GetBatteryVoltage(void);

                     ^

exit status 1
'uint16_t GetBatteryVoltage()' was declared 'extern' and later 'static' [-fpermissive]

**Comment by Securethingsuk** [comment]
This is software for the board manager from the Heltec Automation site. It is not supported here , So I have closed the issue. Simon
